version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnpmjs.org
    depends_on:
      - mysql-db
    volumes:
      - cnpm-files-volume:/var/data/cnpm_data
    ports:
      - "7001:7001"
      - "7002:7002"

  mysql-db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cnpmjs_test
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./docs/db.sql:/docker-entrypoint-initdb.d/cnpm-init.sql
      - cnpm-db-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  cnpm-files-volume:
  cnpm-db-volume:
